---
name: Deploy MkDocs to Github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip3 install -r dockerfiles/slim/requirements.txt 

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.ref }} 
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy to Github pages
        run: mkdocs gh-deploy --force

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the "slim" image
        run: |
          docker build -t dac:slim -f dockerfiles/slim/Dockerfile .
