---
name: Deploy MkDocs to Github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip3 install -r dockerfiles/slim/requirements.txt 

      - name: Deploy to Github pages
        run: mkdocs gh-deploy --force

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the "slim" image
        run: |
          docker build -t dac:slim -f dockerfiles/slim/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dac:slim'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'